# coding: utf-8
from enum import Enum, unique


@unique
class CardAuthenticationResponse(Enum):
    
    FULLY_AUTHENTICATED = "FULLY_AUTHENTICATED"
    AUTHENTICATION_NOT_REQUIRED = "AUTHENTICATION_NOT_REQUIRED"
    NOT_ENROLLED = "NOT_ENROLLED"
    ENROLLMENT_ERROR = "ENROLLMENT_ERROR"
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"

